export const CHANGE_ACCOUNT_TYPE = 'CHANGE_ACCOUNT_TYPE'
export const CHANGE_FORM_PERCENT = 'CHANGE_FORM_PERCENT'
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO'
export const UPDATE_ADDRESS_INFO = 'UPDATE_ADDRESS_INFO'